# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include:
    - "v*"
resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Image
    displayName: Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        MLFLOW_VERSION=$(cat ./mlflow-image/mlflow_version)
        echo $MLFLOW_VERSION
        echo "##vso[task.setvariable variable=tag;isOutput=true]$MLFLOW_VERSION"
      name: mlflow_version
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: './mlflow-image/Dockerfile'
        arguments: '-t mlflow:$(mlflow_version.tag)'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'ECR Push'
        regionName: 'eu-central-1'
        imageSource: 'imagename'
        sourceImageName: 'mlflow'
        sourceImageTag: '$(mlflow_version.tag)'
        repositoryName: 'dna/mlflow'
        pushTag: '$(mlflow_version.tag)'
      displayName: "Push mlflow image"
    - task: AWSShellScript@1
      displayName: Create TF plan
      inputs:
        awsCredentials: 'AWS mlops'
        regionName: 'eu-central-1'
        scriptType: 'inline'
        inlineScript: |
          terraform init
          terraform plan --out plan.tfplan
          terraform apply -auto-approve plan.tfplan
        disableAutoCwd: true
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
        failOnStandardError: true
    - publish: 'infrastructure'
      artifact: 'tf'
