# This pipeline builds the docker image and pushes it to ECR,
# before publishing the helm chart to the same repository

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: HELM_EXPERIMENTAL_OCI
  value: 1 

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true
- task: AWSShellScript@1
  displayName: Save and push chart
  inputs:
    awsCredentials: 'ECR Push'
    regionName: 'eu-central-1'
    scriptType: 'inline'
    inlineScript: |
      echo "Deploying the helm chart to ECR"
      echo $(helm version)
      helm chart save mlflow-chart/ mlflow
      helm chart save mlflow-chart/ 579478677147.dkr.ecr.eu-central-1.amazonaws.com/dna/mlflow:mlflow
      helm chart push 579478677147.dkr.ecr.eu-central-1.amazonaws.com/dna/mlflow:mlflow
    failOnStandardError: true
- task: Docker@2
  displayName: Build docker image
  inputs:
    command: 'build'
    Dockerfile: '**/mlflow-image/Dockerfile'
    tags: 'latest'
    arguments: '-t dna.mlflow'
- task: ECRPushImage@1
  displayName: Push the image to shared ECR
  inputs:
    awsCredentials: 'ECR Push'
    regionName: 'eu-central-1'
    imageSource: 'imagename'
    sourceImageName: 'dna.mlflow'
    repositoryName: 'dna/mlflow'