# backendStore -- Either a filepath, a database or the default value. At present, postgres is the only database engine supported by the official image. Should you want to connect to any other database, please refer to the README.
backendStore:
  # backendStore.filepath -- A local or remote filesystem path (e.g. /mnt/persistent-disk)
  filepath:

  # backendStore.postgres -- A map with the values for (username, password, host, port and database).
  postgres:
    username: mlflow
    password: 1n3Dr5D=OFc0oj*ho4)OVeVqWD6sD3bL
    host: postgres-mlops.cmckd3o7hiss.eu-central-1.rds.amazonaws.com
    port: 5432
    database: mlflow

# defaultArtifactRoot -- A local or remote filepath (e.g. s3://my-bucket). It is mandatory when specifying a database backend store
defaultArtifactRoot: s3://mlops-mlflow-dzelu

# extraArgs -- A map of arguments and values to pass to the `mlflow server` command
extraArgs:
  gunicorn-opts: --log-level debug
  # workers: 2
  # expose-prometheus: yes

replicaCount: 1

image:
  pullPolicy: IfNotPresent

  # image.repository -- The fully qualified name of the docker image to use
  repository: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/dna/mlflow

  # image.tag -- The tag for the repository (e.g. 'latest')
  tag:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # serviceAccount.create -- Specifies whether a service account should be created
  create: true
  # serviceAccount.annotations -- Annotations to add to the service account
  annotations: {}
  # serviceAccount.name -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 5000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  hosts:
    - host: app.hellman.oxygen.dfds.cloud
      paths:
      - path: /mlops/mlflow/
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# set true to expose prometheus
prometheus:
  expose: false

podAnnotations: {}
