{{- if (and .Values.gitSync.enabled .Values.gitSync.ssh.privateKey) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "airflow.gitSync.configMapName" . }}
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
data:
  known_hosts: {{ required "if you set gitSync.enabled and gitSync.ssh.privateKey, you need to set .Values.gitSync.ssh.knownHosts as well" .Values.gitSync.ssh.knownHosts | quote }}
{{- end }}
