{{- if (and .Values.gitSync.enabled .Values.gitSync.ssh.privateKey) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "airflow.gitSync.secretName" . }}
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
type: Opaque
data:
  gitSshKey: {{ .Values.gitSync.ssh.privateKey | b64enc | quote }}
{{- end }}
