apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
data:
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__KUBERNETES__NAMESPACE: {{ .Release.Namespace }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: {{ .Values.images.airflow.repository }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: {{ .Values.images.airflow.tag }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_PULL_POLICY: {{ .Values.images.airflow.pullPolicy }}
  AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF: {{ include "airflow.fullname" . }}
  AIRFLOW__KUBERNETES__ENV_FROM_SECRET_REF: {{ include "airflow.fullname" . }}
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: {{ include "airflow.worker.serviceAccountName" . }}

  {{- if .Values.gitSync.enabled }}
  GIT_SYNC_WAIT: "60"
  AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "false"
  AIRFLOW__KUBERNETES__GIT_SYNC_INIT_CONTAINER_NAME: git-clone

  GIT_SYNC_REPO: {{ required "When you enable gitSync, you need to specify the value config.GIT_SYNC_REPO as well" .Values.config.GIT_SYNC_REPO }}
  AIRFLOW__KUBERNETES__GIT_REPO: {{ .Values.config.GIT_SYNC_REPO }}

  GIT_SYNC_BRANCH: {{ required "When you enable gitSync, you need to specify the value config.GIT_SYNC_BRANCH as well" .Values.config.GIT_SYNC_BRANCH }}
  AIRFLOW__KUBERNETES__GIT_BRANCH: {{ .Values.config.GIT_SYNC_BRANCH }}

  GIT_SYNC_ROOT: {{ .Values.gitSync.root }}
  AIRFLOW__KUBERNETES__GIT_SYNC_ROOT: {{ .Values.gitSync.root }}

  GIT_SYNC_DEST: {{ .Values.gitSync.dest }}
  AIRFLOW__KUBERNETES__GIT_SYNC_DEST: {{ .Values.gitSync.dest }}

  GIT_SYNC_DEPTH: "1"
  AIRFLOW__KUBERNETES__GIT_SYNC_DEPTH: "1"

  AIRFLOW__KUBERNETES__GIT_SYNC_CONTAINER_REPOSITORY: {{ .Values.images.gitSync.repository }}
  AIRFLOW__KUBERNETES__GIT_SYNC_CONTAINER_TAG: {{ .Values.images.gitSync.tag }}

  #
  # Mirror GIT_SYNC_ config options set by the Chart user
  #
  AIRFLOW__KUBERNETES__GIT_SUBPATH: {{ default "" .Values.config.GIT_SYNC_SUBPATH | quote }}
  AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: {{ include "airflow.dagsFolder" . }}


  {{- if .Values.gitSync.ssh.privateKey }}
  GIT_SYNC_SSH: "true"
  GIT_SSH_KEY_FILE: "/etc/git-secret/gitSshKey"
  AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: {{ include "airflow.gitSync.secretName" . }}

  GIT_KNOWN_HOSTS: "true"
  GIT_SSH_KNOWN_HOSTS_FILE: "/etc/git-config/known_hosts"
  AIRFLOW__KUBERNETES__GIT_SSH_KNOWN_HOSTS_CONFIGMAP_NAME: {{ include "airflow.gitSync.configMapName" . }}
  {{- end }}



  AIRFLOW__KUBERNETES__GIT_USER: {{ default "" .Values.config.GIT_SYNC_USER | quote }}
  AIRFLOW__KUBERNETES__GIT_PASSWORD: {{ default "" .Values.config.GIT_SYNC_PASSWORD | quote }}

  {{- else }}
  AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "true"
  {{- end }}

  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
