kind: Secret
apiVersion: v1
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
type: Opaque
data:
  FERNET_KEY: {{ (default (randAlphaNum 32 | b64enc) .Values.secrets.FERNET_KEY) | b64enc | quote }}
  AIRFLOW__WEBSERVER__SECRET_KEY: {{ (default (randAlphaNum 32 | b64enc) .Values.secrets.AIRFLOW__WEBSERVER__SECRET_KEY) | b64enc | quote }}

  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
