version: "3.8"
services:
  mlflow:
    build: .
    command: --host=0.0.0.0 --port=80 --backend-store-uri=postgresql://postgres:postgres@db:5432 --default-artifact-root=file//var/mlflow/mlruns
    ports:
      - "5000:80"
    depends_on:
      - db
    volumes:
      - ./mlruns:/var/mlflow/mlruns
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  db-data:
