apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-webserver
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
    {{- include "airflow.webserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "airflow.global.selectorLabels" . | nindent 6 }}
      {{- include "airflow.webserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.global.selectorLabels" . | nindent 8 }}
        {{- include "airflow.webserver.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "airflow.webserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.gitSync.enabled }}
      {{ include "airflow.gitSync.volumes" . | nindent 6 }}
      initContainers:
        {{ include "airflow.gitSync.initContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: webserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}"
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          args:
            - webserver
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources.webserver | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "airflow.fullname" . }}
            - configMapRef:
                name: {{ include "airflow.fullname" . }}
        {{- if .Values.gitSync.enabled }}
          volumeMounts:
            - name: git-dags
              mountPath: {{ include "airflow.dagsFolder" . }}
        {{ include "airflow.gitSync.container" . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
