{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow.webserver.serviceAccountName" . }}
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
    {{- include "airflow.webserver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.webserver.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
