apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-webserver
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
    {{- include "airflow.webserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webserver.type }}
  ports:
    - port: {{ .Values.service.webserver.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airflow.global.selectorLabels" . | nindent 4 }}
    {{- include "airflow.webserver.selectorLabels" . | nindent 4 }}
