kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "airflow.fullname" . }}-worker
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
    {{- include "airflow.worker.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - list
      - get
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
