apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "airflow.fullname" . }}-worker
  labels:
    {{- include "airflow.global.labels" . | nindent 4 }}
    {{- include "airflow.worker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "airflow.fullname" . }}-worker
subjects:
- kind: ServiceAccount
  name: {{ template "airflow.worker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
